### ISSUE TITLE
SL mistake "set contact distance"

### ISSUE THREAD

**Issue by Shne1der** [realitymod/Manual#11]
**This part to "Squad Leader" is obsolet. Need to edit:**

_3. Now hold down the main radio key (Q) and select the SET CONTACT DISTANCE button, then select the target's distance from the list._

**Comment by Shne1der** [comment]
nobody here?

**Comment by WouterJansen** [comment]
Done!We only update manual for new releases, hence it took so long for us to notice your Issue. Sorry!
