### ISSUE TITLE
Headers displays README on gitbook.io

### ISSUE THREAD

**Issue by jpaulomotta** [realitymod/Manual#12]
Hello,

I'm just reporting this strange error that showed up in the manual when I accesed it via the game launcher.

All the headings are showing as "README" as you can see in the screenshot attached.

![image](https://user-images.githubusercontent.com/1813007/72475449-ae460500-37c9-11ea-9261-34a1be048b86.png)

The game launcher is opening the manual at the url https://realitymod.gitbook.io/pr-manual/en/the_basics 

The version that is on this repository description is working fine, under the location  https://www.realitymod.com/manual/en/.

**Comment by WouterJansen** [comment]
Known issue. we moved our hosting to realitymod.com/manual. Launcher just needs to be updated to update the link.
