### ISSUE TITLE
Information Order

### ISSUE THREAD

**Issue by CameI** [realitymod/Manual#3]
I am currently working on the Spanish translation of the manual and, working on the original text in English, a few times I have thought that the order in which information appears could be modified to make it more intuitive. The general rule would be to put more general and relevant information first (to give a better and more solid general understanding) and add other bits of complimentary information afterwards.

For example, while talking about the different game modes, wouldn't it make more sense to sort them according to popularity? Like, placing AAS, INS and COOP on top, and then C&C, Skirmish and Vehicle Warfare afterwards? Or, when talking about the SL, wouldn't it be more intuitive to talk about Rally Points before talking about the GLTD? Or, listing the available deployable structures before explaining how to build them? And so on. I have seen a few occurrences of this and you get the idea.

Similarly, when describing the available kits, while technically accurate, I thought it is kind of cumbersome having so many categories (7): Spawn-able Unlimited kits, Spawn-able Special Kits, Spawn-able Infantry, Request-able Unlimited Kits, Request-able Special Kits, Request-able Infantry and Pick-up kits. I am not sure these categories are relevant for the average player.

In the Spanish version I am making, I simplified all these categories and simply merged them, dividing them only in 2 categories: Standard Kits (appear in spawn menu) and Specialist Kits (must be requested), and then having a simple table with detailed info about their limitation per team. It kind of feels more clean to me.

I can post a sample of this, but it is as of now only in Spanish.

Any comments on this would be appreciated.

**Comment by WouterJansen** [comment]
Please don't alter the structure for translations. Stick to the way the English variant is now. I'm not saying it's not up improvement, but having the translations being different causes issues for future updates. Specially the kits, you are changing the explanation of manual. Don't do that please.

**Comment by CameI** [comment]
@WouterJansen, you are right, I didn't think of it that way.

Put that way, I realise that before doing the Spanish translation, what I need to do is to suggest changes to the English version. I do think the manual can see some improvement.

How do I do this? Should I create a new branch off the English version and then submit pull requests?

And one more question, what is the best place to ask specific things about bits of information in the manual, here or in realitymod forums?

**Comment by WouterJansen** [comment]
best of the forums I think, we read that the most. But both are fine. You can use the issues here on github to report possible improvements like Turista did fore example for your suggestions.
