### ISSUE TITLE
Rename "Book" from the default HonKit name

### ISSUE THREAD

**Issue by Strepto** [realitymod/Manual#31]
Hey! I tried googling the PR manual, and found this:

![image](https://user-images.githubusercontent.com/3185998/196004791-131db5d6-424b-4771-96c3-8a64c7cf9b36.png)

A simple change in the book.json file by adding 

```json
{    
     "title": "Project Reality Manual",
     "plugins": [ // Snip
```

 would change the title to `About - Project Reality Manual - Project Reality`, and make it more readable and searchable. Also improves the tab title while the manual is open.

I have _not_ found how to translate the title, but I feel that this is better than the default "HonKit".

**Comment by UTurista** [comment]
> I have not found how to translate the title, but I feel that this is better than the default "HonKit".

This can be achieved by creating a `book.json` in each of the language folders (eg: `es/book.json` , `fr/book.json` which will override the "global" one.
