### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by CameI** [realitymod/Manual#5]
Why are the icons and images in /assets not showing up in the manual?

**Comment by WouterJansen** [comment]
Be more specific? not showing up where.

**Comment by CameI** [comment]
When I "preview" the different parts of the manual, I don't get any icon whatsoever displayed. See screenshot below. Shouldn't they appear?

Also, I thought the image file names had a missing underscore because, as you can see in the screenshot, file names with spaces seem to show the whole img tag in the preview, which doesn't appear with the Known Coalition Cache icon, whose file name has no spaces in it.

![screenshot 2018-02-14 12 49 03](https://user-images.githubusercontent.com/12743976/36200849-9fd143a6-1186-11e8-8c01-d96637ca3a2a.png)

**Comment by UTurista** [comment]
That preview comes from Github which seems to have a different markdown parser from Gitbook, which is the one that matters to us.

If you see [here](https://realitymod.gitbooks.io/pr-manual/content/en/game_modes/#insurgency), the images are displayed correctly.

I might try and see if I can have images working on both but this is a non issue.

**Comment by CameI** [comment]
Oh, I see.
And what would be the easiest way to "preview" in Gitbook the versions I work on GitHub?

**Comment by UTurista** [comment]
Planned to link it but forgot, [editor here](https://www.gitbook.com/editor). Alternatively, if you don't want to install software, you can create your own gitbook based on your repository and preview directly online (thou the software may be easier).

If you find that images may appear correctly on both github and gitbook do a Pull request with those changes.
