### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Nabils454** [realitymod/Manual#51]
[they give me this error :
8962: failed writing login cookie]

---
⚠ *Do not edit this section.*

* Version: 'Sat Jun 24 2023 17:15:56 GMT 0200 (Central European Summer Time)'
* Language: 'en'
* Page: 'README.md'

**Comment by WouterJansen** [comment]
I am assuming this is game error and does not have anything to do with the manual? 

https://www.realitymod.org/forum/showthread.php?t=152517
